### ISSUE TITLE
CompilerOptions has webpack: true when creating library

### ISSUE THREAD

**Issue by altanbgn** [brocoders/nestjs-boilerplate#1679]
** Describing the bug **
My project is using TypeORM and it might just be typeorm's bug. I am not really sure.

I created a library inside my project using `nest g library my-library`. Library was created and I have written my code. Everything was going great until when I tried to run it. At first TypeORM says that it can't connect with the database which is weird for an error message when in it did connect but couldn't run any queries. I've been hunting and comparing the file for 30 minutes and found somehow `nest-cli.json` has a `webpack: true` in the `compilerOptions`. This made TypeORM impossible to find it's entity files which causes a weird error message of "can't connect to the database".

I will report this issue to TypeORM as well.

** Question **
Is it really necessary to have `compilerOptions` to have `webpack: true`? I want to know more and what does it do? It seems to me that libraries work regardless of this option being true or false.

** Error message **
```
> nest start

webpack 5.93.0 compiled successfully in 1808 ms
query: SELECT * FROM current_schema()
query: SELECT * FROM current_schema()
query: SELECT * FROM current_schema()
query: SELECT * FROM current_schema()
query: SELECT * FROM current_schema()
query: SELECT * FROM current_schema()
query: SELECT * FROM current_schema()
query: SELECT * FROM current_schema()
query: SELECT * FROM current_schema()
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [NestFactory] Starting Nest application...
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [InstanceLoader] XypModule dependencies initialized +0ms
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [InstanceLoader] HttpModule dependencies initialized +0ms
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [InstanceLoader] TerminusModule dependencies initialized +0ms
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [InstanceLoader] XypModule dependencies initialized +0ms
[Nest] 66357  - 08/21/2024, 10:37:03 AM     LOG [InstanceLoader] HealthModule dependencies initialized +0ms
[Nest] 66357  - 08/21/2024, 10:37:03 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
/home/altanbgn/Personal/work/xyp-service/src/modules/client/client.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at tryToRequire (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:35:25)
    at <anonymous> (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/DirectoryExportedClassesLoader.ts:57:45)
[Nest] 66357  - 08/21/2024, 10:37:03 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
/home/altanbgn/Personal/work/xyp-service/src/modules/client/client.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at tryToRequire (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:35:25)
    at <anonymous> (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/DirectoryExportedClassesLoader.ts:57:45)
[Nest] 66357  - 08/21/2024, 10:37:03 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (3)...
/home/altanbgn/Personal/work/xyp-service/src/modules/client/client.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at tryToRequire (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:35:25)
    at <anonymous> (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/DirectoryExportedClassesLoader.ts:57:45)
[Nest] 66357  - 08/21/2024, 10:37:03 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
/home/altanbgn/Personal/work/xyp-service/src/modules/client/client.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at tryToRequire (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:35:25)
    at <anonymous> (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/DirectoryExportedClassesLoader.ts:57:45)
[Nest] 66357  - 08/21/2024, 10:37:03 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (5)...
/home/altanbgn/Personal/work/xyp-service/src/modules/client/client.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at tryToRequire (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:35:25)
    at <anonymous> (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/DirectoryExportedClassesLoader.ts:57:45)
[Nest] 66357  - 08/21/2024, 10:37:03 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (6)...
/home/altanbgn/Personal/work/xyp-service/src/modules/client/client.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at tryToRequire (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:35:25)
    at <anonymous> (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/DirectoryExportedClassesLoader.ts:57:45)
[Nest] 66357  - 08/21/2024, 10:37:03 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (7)...
/home/altanbgn/Personal/work/xyp-service/src/modules/client/client.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at tryToRequire (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:35:25)
    at <anonymous> (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/DirectoryExportedClassesLoader.ts:57:45)
[Nest] 66357  - 08/21/2024, 10:37:03 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
/home/altanbgn/Personal/work/xyp-service/src/modules/client/client.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at tryToRequire (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:35:25)
    at <anonymous> (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/DirectoryExportedClassesLoader.ts:57:45)
[Nest] 66357  - 08/21/2024, 10:37:03 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (9)...
/home/altanbgn/Personal/work/xyp-service/src/modules/client/client.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at tryToRequire (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:35:25)
    at <anonymous> (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/DirectoryExportedClassesLoader.ts:57:45)
[Nest] 66357  - 08/21/2024, 10:37:03 AM   ERROR [ExceptionHandler] Cannot use import statement outside a module
/home/altanbgn/Personal/work/xyp-service/src/modules/client/client.entity.ts:1
import {
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at tryToRequire (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:21:17)
    at importOrRequireFile (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/ImportUtils.ts:35:25)
    at <anonymous> (/home/altanbgn/Personal/work/xyp-service/node_modules/.pnpm/typeorm@0.3.20_pg@8.12.0_ts-node@10.9.2_@types+node@22.4.1_typescript@5.5.4_/node_modules/typeorm/util/src/util/DirectoryExportedClassesLoader.ts:57:45)
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by Shchepotin** [comment]
Hi @altanbgn! We already have a similar issue. This is TypeORM bug https://github.com/brocoders/nestjs-boilerplate/issues/1218#issuecomment-1807754603
