### ISSUE TITLE
EntityMetadataNotFoundError: No metadata for "Role" was found.

### ISSUE THREAD

**Issue by its-monotype** [brocoders/nestjs-boilerplate#878]
```powershell
╰─❯ npm run seed:run

> nestjs-boilerplate@0.0.1 seed:run
> ts-node -r tsconfig-paths/register ./src/database/seeds/run-seed.ts

[Nest] 2808  - 20/02/2023, 18:21:00     LOG [NestFactory] Starting Nest application...
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] SeedModule dependencies initialized +19ms
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
query: SELECT * FROM current_schema()
query: SELECT version();
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] TypeOrmCoreModule dependencies initialized +269ms
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] RoleSeedModule dependencies initialized +0ms
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] StatusSeedModule dependencies initialized +1ms
[Nest] 2808  - 20/02/2023, 18:21:00     LOG [InstanceLoader] UserSeedModule dependencies initialized +0ms
C:\Users\itsmo\Desktop\my-app\node_modules\src\data-source\DataSource.ts:438
        if (!metadata) throw new EntityMetadataNotFoundError(target)
                             ^
EntityMetadataNotFoundError: No metadata for "Role" was found.
    at DataSource.getMetadata (C:\Users\itsmo\Desktop\my-app\node_modules\src\data-source\DataSource.ts:438:30)
    at Repository.get metadata [as metadata] (C:\Users\itsmo\Desktop\my-app\node_modules\src\repository\Repository.ts:53:40)
    at Repository.count (C:\Users\itsmo\Desktop\my-app\node_modules\src\repository\Repository.ts:467:40)
    at RoleSeedService.run (C:\Users\itsmo\Desktop\my-app\src\database\seeds\role\role-seed.service.ts:15:45)
    at runSeed (C:\Users\itsmo\Desktop\my-app\src\database\seeds\run-seed.ts:11:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    ```

**Comment by its-monotype** [comment]
Maybe because createTypeOrmOptions __dirname=C:\Users\user\my-app\dist\database but entities not located inside database folder

**Comment by its-monotype** [comment]
However with autoLoadEntities = true, everything works.

**Comment by its-monotype** [comment]
I just did steps in the readme for comfort development and facing this issue

**Comment by mustakim** [comment]
I am also facing this issue when run `npm run seed:run`

**Comment by mustakim** [comment]
@its-monotype , did you get any solution for the issue ?

**Comment by its-monotype** [comment]
> @its-monotype , did you get any solution for the issue ?

Sadly not, maybe @Shchepotin will help us, idk, I even though to migrate whole project to Prisma

**Comment by mustakim** [comment]
@Shchepotin, 

My current node version is `16.15.1`
Yes, I am running my project in windows.
No, I am not using docker.

**Comment by Shchepotin** [comment]
@mustakim please show output `npm run migration:run`

**Comment by mustakim** [comment]
@Shchepotin, here is the output

![image](https://user-images.githubusercontent.com/7153998/220889739-88660752-ea44-4233-abfa-c141ae8b8293.png)

**Comment by Shchepotin** [comment]
@mustakim do you make any changes in project?

**Comment by mustakim** [comment]
@Shchepotin, no changes without configuring the env. Mentioning that, I am using the `main` branch. even, though I didn't change the git repository yet.

**Comment by Shchepotin** [comment]
@mustakim could you please install typeorm 0.3.11:

1. change version in `package.json`
1. run `npm i`

I think it's because of this issue https://github.com/typeorm/typeorm/issues/9772

Note: on Linux and MacOS I can't catch this problem and everything is working fine.

**Comment by mustakim** [comment]
@Shchepotin, 

I will try this. I have switched to ubuntu on my other device and here it's working fine.
