### ISSUE TITLE
throws an error that the database <db> does not exist

### ISSUE THREAD

**Issue by Yassin-H-Rassul** [brocoders/nestjs-boilerplate#960]
**Describe the bug**
It throws an error that the database does not exist, when in fact it does exist when I run "npm run start:dev" but inside docker, in logs, it gives me this error inside the Postgres Service:

`2023-04-21 20:16:52 PostgreSQL Database directory appears to contain a database; Skipping initialization 2023-04-21 20:16:52 
2023-04-21 19:26:41 2023-04-21 16:26:41.482 UTC [1] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-04-21 19:26:41 2023-04-21 16:26:41.483 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-04-21 19:26:41 2023-04-21 16:26:41.483 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-04-21 19:26:41 2023-04-21 16:26:41.497 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-04-21 19:26:41 2023-04-21 16:26:41.541 UTC [24] LOG:  database system was shut down at 2023-04-21 16:26:37 UTC
2023-04-21 19:26:41 2023-04-21 16:26:41.589 UTC [1] LOG:  database system is ready to accept connections
_2023-04-21 19:27:07 2023-04-21 16:27:07.120 UTC [29] FATAL:  database "topen_db_new" does not exist
2023-04-21 19:28:35 2023-04-21 16:28:35.842 UTC [31] FATAL:  database "topen_db_new" does not exist_
2023-04-21 19:28:39 2023-04-21 16:28:39.946 UTC [1] LOG:  received fast shutdown request
2023-04-21 19:28:39 2023-04-21 16:28:39.954 UTC [1] LOG:  aborting any active transactions
2023-04-21 19:28:39 2023-04-21 16:28:39.957 UTC [1] LOG:  background worker "logical replication launcher" (PID 27) exited with exit code 1`

and inside Api service logs it gives this error:

`2023-04-21 20:16:37 wait-for-it.sh: waiting 15 seconds for postgres:5432
2023-04-21 20:16:37 wait-for-it.sh: postgres:5432 is available after 0 seconds
2023-04-21 20:16:41 error: database "topen_db_new" does not exist
2023-04-21 20:16:41     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/src/parser.ts:369:69)
2023-04-21 20:16:41     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/src/parser.ts:188:21)
2023-04-21 20:16:41     at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:103:30)
2023-04-21 20:16:41     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)
2023-04-21 20:16:41     at Socket.emit (node:events:513:28)
2023-04-21 20:16:41     at Socket.emit (node:domain:489:12)
2023-04-21 20:16:41     at addChunk (node:internal/streams/readable:324:12)
2023-04-21 20:16:41     at readableAddChunk (node:internal/streams/readable:297:9)
2023-04-21 20:16:41     at Socket.Readable.push (node:internal/streams/readable:234:10)
2023-04-21 20:16:41     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
2023-04-21 20:16:41   length: 97,
2023-04-21 20:16:41   severity: 'FATAL',
2023-04-21 20:16:41   code: '3D000',
2023-04-21 20:16:41   detail: undefined,
2023-04-21 20:16:41   hint: undefined,
2023-04-21 20:16:41   position: undefined,
2023-04-21 20:16:41   internalPosition: undefined,
2023-04-21 20:16:41   internalQuery: undefined,
2023-04-21 20:16:41   where: undefined,
2023-04-21 20:16:41   schema: undefined,
2023-04-21 20:16:41   table: undefined,
2023-04-21 20:16:41   column: undefined,
2023-04-21 20:16:41   dataType: undefined,
2023-04-21 20:16:41   constraint: undefined,
2023-04-21 20:16:41   file: 'postinit.c',
2023-04-21 20:16:37 
2023-04-21 20:16:37 > nestjs-boilerplate@0.0.1 migration:run
2023-04-21 20:16:37 > npm run typeorm -- --dataSource=src/database/data-source.ts migration:run
2023-04-21 20:16:37 
2023-04-21 20:16:38 
2023-04-21 20:16:38 > nestjs-boilerplate@0.0.1 typeorm
2023-04-21 20:16:38 > env-cmd ts-node -r tsconfig-paths/register ./node_modules/typeorm/cli.js --dataSource=src/database/data-source.ts migration:run
2023-04-21 20:16:38 
2023-04-21 20:16:40 Error during migration run:
`

**Desktop 
 - OS: [e.g. Windows]
 - NodeJS Version [e.g. 18.16.0]

**Comment by Shchepotin** [comment]
@Yassin-H-Rassul 

> in fact it does exist

Please show me that this DB exists. Just print all databases in your PostgreSQL.

**Comment by Yassin-H-Rassul** [comment]
that is the image of the services running:

[https://drive.google.com/file/d/1WCX9wdcPd3JA69EpRs5KJWRENcXDVrbu/view?usp=share_link](url)

and the Postgres Service is running perfectly, and that is my env and env example: 

NODE_ENV=development
APP_PORT=3000
APP_NAME="NestJS API"
API_PREFIX=api
APP_FALLBACK_LANGUAGE=en
APP_HEADER_LANGUAGE=x-custom-lang
FRONTEND_DOMAIN=http://localhost:3000
BACKEND_DOMAIN=http://localhost:3000

DATABASE_TYPE=postgres
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_USERNAME=postgres
DATABASE_NAME=topen_db_new
DATABASE_SYNCHRONIZE=false
DATABASE_MAX_CONNECTIONS=100
DATABASE_SSL_ENABLED=false
DATABASE_REJECT_UNAUTHORIZED=false
DATABASE_CA=
DATABASE_KEY=
DATABASE_CERT=

# Support "local", "s3"
FILE_DRIVER=local
ACCESS_KEY_ID=
SECRET_ACCESS_KEY=
AWS_S3_REGION=
AWS_DEFAULT_S3_BUCKET=

MAIL_HOST=maildev
MAIL_PORT=1025
MAIL_USER=
MAIL_PASSWORD=
MAIL_IGNORE_TLS=true
MAIL_SECURE=false
MAIL_REQUIRE_TLS=false
MAIL_DEFAULT_EMAIL=noreply@example.com
MAIL_DEFAULT_NAME=Api
MAIL_CLIENT_PORT=1080


GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

APPLE_APP_AUDIENCE=[]

TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=

WORKER_HOST=redis://redis:6379/1



and in API Service I have this error: 

2023-04-25 17:33:29 wait-for-it.sh: waiting 15 seconds for postgres:5432
2023-04-25 17:33:32 wait-for-it.sh: postgres:5432 is available after 3 seconds
2023-04-25 17:33:38 error: database "topen_db_new" does not exist

**Comment by Shchepotin** [comment]
@Yassin-H-Rassul This is not exactly what I asked. Please open Adminer http://localhost:8080 and connect to PostgreSQL with your credentials and send me screen of your databases

**Comment by Yassin-H-Rassul** [comment]
> @Yassin-H-Rassul This is not exactly what I asked. Please open Adminer http://localhost:8080 and connect to PostgreSQL with your credentials and send me screenshot of your databases


sorry but I don't know how to connect to db using Adminer, that is the screenshot: 
https://drive.google.com/file/d/1jeDVOi5i40PvDWb4-sRB4Xp_srlWDxRy/view?usp=share_link

but I can show you PgAdmin where I connected the codebase to the database locally on my computer, no on docker:

https://drive.google.com/file/d/1IheKmca2nITp3OWtUyTLzbuyPuAYPERg/view?usp=share_link
